// SpellTris Language Learning Vocabulary Database
// Curated list of trilingual words (English, Spanish, German)
// Tagged with levels, grammar types, and themes.

const VOCABULARY = [
    // --- COLORS ---
    { en: "blue", es: "azul", de: "blau", level: "beginner", type: "adjective", theme: "colors" },
    { en: "rose", es: "rosa", de: "rosa", level: "beginner", type: "adjective", theme: "colors" },
    { en: "grey", es: "gris", de: "grau", level: "beginner", type: "adjective", theme: "colors" },
    { en: "gray", es: "gris", de: "grau", level: "beginner", type: "adjective", theme: "colors" },
    { en: "green", es: "verde", de: "grün", level: "beginner", type: "adjective", theme: "colors" },
    { en: "black", es: "negro", de: "schwarz", level: "beginner", type: "adjective", theme: "colors" },
    { en: "white", es: "blanco", de: "weiss", level: "beginner", type: "adjective", theme: "colors" },
    { en: "yellow", es: "amarillo", de: "gelb", level: "intermediate", type: "adjective", theme: "colors" },
    { en: "brown", es: "marrón", de: "braun", level: "beginner", type: "adjective", theme: "colors" },
    { en: "orange", es: "naranja", de: "orange", level: "intermediate", type: "adjective", theme: "colors" },

    // --- ANIMALS ---
    { en: "fish", es: "pez", de: "fisch", level: "beginner", type: "noun", theme: "animals" },
    { en: "bird", es: "ave", de: "vogel", level: "beginner", type: "noun", theme: "animals" },
    { en: "frog", es: "rana", de: "frosch", level: "intermediate", type: "noun", theme: "animals" },
    { en: "wolf", es: "lobo", de: "wolf", level: "intermediate", type: "noun", theme: "animals" },
    { en: "bear", es: "oso", de: "bär", level: "beginner", type: "noun", theme: "animals" },
    { en: "duck", es: "pato", de: "ente", level: "beginner", type: "noun", theme: "animals" },
    { en: "lion", es: "león", de: "löwe", level: "beginner", type: "noun", theme: "animals" },
    { en: "dog", es: "perro", de: "hund", level: "beginner", type: "noun", theme: "animals" },
    { en: "cat", es: "gato", de: "katze", level: "beginner", type: "noun", theme: "animals" },
    { en: "horse", es: "caballo", de: "pferd", level: "beginner", type: "noun", theme: "animals" },
    { en: "mouse", es: "ratón", de: "maus", level: "beginner", type: "noun", theme: "animals" },
    { en: "sheep", es: "oveja", de: "schaf", level: "intermediate", type: "noun", theme: "animals" },
    { en: "snake", es: "serpiente", de: "schlange", level: "intermediate", type: "noun", theme: "animals" },
    { en: "spider", es: "araña", de: "spinne", level: "intermediate", type: "noun", theme: "animals" },
    { en: "monkey", es: "mono", de: "affe", level: "intermediate", type: "noun", theme: "animals" },

    // --- FOOD ---
    { en: "milk", es: "leche", de: "milch", level: "beginner", type: "noun", theme: "food" },
    { en: "meat", es: "carne", de: "fleisch", level: "beginner", type: "noun", theme: "food" },
    { en: "beer", es: "cerveza", de: "bier", level: "beginner", type: "noun", theme: "food" },
    { en: "wine", es: "vino", de: "wein", level: "beginner", type: "noun", theme: "food" },
    { en: "bread", es: "pan", de: "brot", level: "beginner", type: "noun", theme: "food" },
    { en: "apple", es: "manzana", de: "apfel", level: "beginner", type: "noun", theme: "food" },
    { en: "cheese", es: "queso", de: "käse", level: "beginner", type: "noun", theme: "food" },
    { en: "water", es: "agua", de: "wasser", level: "beginner", type: "noun", theme: "food" },
    { en: "rice", es: "arroz", de: "reis", level: "beginner", type: "noun", theme: "food" },
    { en: "salt", es: "sal", de: "salz", level: "beginner", type: "noun", theme: "food" },
    { en: "soup", es: "sopa", de: "suppe", level: "beginner", type: "noun", theme: "food" },
    { en: "fruit", es: "fruta", de: "obst", level: "beginner", type: "noun", theme: "food" },
    { en: "onion", es: "cebolla", de: "zwiebel", level: "intermediate", type: "noun", theme: "food" },
    { en: "grape", es: "uva", de: "traube", level: "intermediate", type: "noun", theme: "food" },

    // --- HOME ---
    { en: "home", es: "casa", de: "heim", level: "beginner", type: "noun", theme: "home" },
    { en: "house", es: "casa", de: "haus", level: "beginner", type: "noun", theme: "home" },
    { en: "door", es: "puerta", de: "tür", level: "beginner", type: "noun", theme: "home" },
    { en: "wall", es: "pared", de: "wand", level: "beginner", type: "noun", theme: "home" },
    { en: "roof", es: "techo", de: "dach", level: "intermediate", type: "noun", theme: "home" },
    { en: "bed", es: "cama", de: "bett", level: "beginner", type: "noun", theme: "home" },
    { en: "room", es: "cuarto", de: "zimmer", level: "beginner", type: "noun", theme: "home" },
    { en: "table", es: "mesa", de: "tisch", level: "beginner", type: "noun", theme: "home" },
    { en: "chair", es: "silla", de: "stuhl", level: "beginner", type: "noun", theme: "home" },
    { en: "book", es: "libro", de: "buch", level: "beginner", type: "noun", theme: "home" },
    { en: "key", es: "llave", de: "schlüssel", level: "beginner", type: "noun", theme: "home" },
    { en: "lamp", es: "lámpara", de: "lampe", level: "beginner", type: "noun", theme: "home" },
    { en: "plate", es: "plato", de: "teller", level: "beginner", type: "noun", theme: "home" },
    { en: "spoon", es: "cuchara", de: "löffel", level: "intermediate", type: "noun", theme: "home" },
    { en: "knife", es: "cuchillo", de: "messer", level: "intermediate", type: "noun", theme: "home" },

    // --- SPORTS & LEISURE ---
    { en: "game", es: "juego", de: "spiel", level: "beginner", type: "noun", theme: "sports" },
    { en: "ball", es: "pelota", de: "ball", level: "beginner", type: "noun", theme: "sports" },
    { en: "play", es: "jugar", de: "spielen", level: "beginner", type: "verb", theme: "sports" },
    { en: "swim", es: "nadar", de: "schwimmen", level: "intermediate", type: "verb", theme: "sports" },
    { en: "run", es: "correr", de: "rennen", level: "beginner", type: "verb", theme: "sports" },
    { en: "jump", es: "saltar", de: "springen", level: "intermediate", type: "verb", theme: "sports" },
    { en: "goal", es: "meta", de: "ziel", level: "intermediate", type: "noun", theme: "sports" },
    { en: "walk", es: "caminar", de: "gehen", level: "beginner", type: "verb", theme: "sports" },
    { en: "climb", es: "escalar", de: "klettern", level: "advanced", type: "verb", theme: "sports" },
    { en: "dance", es: "bailar", de: "tanzen", level: "beginner", type: "verb", theme: "sports" },
    { en: "sport", es: "deporte", de: "sport", level: "beginner", type: "noun", theme: "sports" },

    // --- NATURE ---
    { en: "wind", es: "viento", de: "wind", level: "beginner", type: "noun", theme: "nature" },
    { en: "rain", es: "lluvia", de: "regen", level: "beginner", type: "noun", theme: "nature" },
    { en: "fire", es: "fuego", de: "feuer", level: "beginner", type: "noun", theme: "nature" },
    { en: "sand", es: "arena", de: "sand", level: "beginner", type: "noun", theme: "nature" },
    { en: "land", es: "tierra", de: "land", level: "beginner", type: "noun", theme: "nature" },
    { en: "star", es: "estrella", de: "stern", level: "beginner", type: "noun", theme: "nature" },
    { en: "tree", es: "árbol", de: "baum", level: "beginner", type: "noun", theme: "nature" },
    { en: "leaf", es: "hoja", de: "blatt", level: "intermediate", type: "noun", theme: "nature" },
    { en: "moon", es: "luna", de: "mond", level: "beginner", type: "noun", theme: "nature" },
    { en: "sun", es: "sol", de: "sonne", level: "beginner", type: "noun", theme: "nature" },
    { en: "lake", es: "lago", de: "see", level: "beginner", type: "noun", theme: "nature" },
    { en: "river", es: "río", de: "fluss", level: "intermediate", type: "noun", theme: "nature" },
    { en: "cloud", es: "nube", de: "wolke", level: "intermediate", type: "noun", theme: "nature" },
    { en: "stone", es: "piedra", de: "stein", level: "intermediate", type: "noun", theme: "nature" },

    // --- BODY ---
    { en: "hand", es: "mano", de: "hand", level: "beginner", type: "noun", theme: "body" },
    { en: "foot", es: "pie", de: "fuss", level: "beginner", type: "noun", theme: "body" },
    { en: "head", es: "cabeza", de: "kopf", level: "beginner", type: "noun", theme: "body" },
    { en: "hair", es: "pelo", de: "haar", level: "beginner", type: "noun", theme: "body" },
    { en: "face", es: "cara", de: "gesicht", level: "intermediate", type: "noun", theme: "body" },
    { en: "nose", es: "nariz", de: "nase", level: "beginner", type: "noun", theme: "body" },
    { en: "mouth", es: "boca", de: "mund", level: "beginner", type: "noun", theme: "body" },
    { en: "heart", es: "corazón", de: "herz", level: "beginner", type: "noun", theme: "body" },
    { en: "arm", es: "brazo", de: "arm", level: "beginner", type: "noun", theme: "body" },
    { en: "leg", es: "pierna", de: "bein", level: "beginner", type: "noun", theme: "body" },
    { en: "body", es: "cuerpo", de: "körper", level: "intermediate", type: "noun", theme: "body" },
    { en: "finger", es: "dedo", de: "finger", level: "intermediate", type: "noun", theme: "body" },

    // --- GENERAL / EMOTIONS / OTHER ---
    { en: "love", es: "amor", de: "liebe", level: "beginner", type: "noun", theme: "general" },
    { en: "time", es: "tiempo", de: "zeit", level: "beginner", type: "noun", theme: "general" },
    { en: "year", es: "año", de: "jahr", level: "beginner", type: "noun", theme: "general" },
    { en: "week", es: "semana", de: "woche", level: "beginner", type: "noun", theme: "general" },
    { en: "life", es: "vida", de: "leben", level: "beginner", type: "noun", theme: "general" },
    { en: "work", es: "trabajo", de: "arbeit", level: "beginner", type: "noun", theme: "general" },
    { en: "good", es: "bueno", de: "gut", level: "beginner", type: "adjective", theme: "general" },
    { en: "bad", es: "malo", de: "schlecht", level: "beginner", type: "adjective", theme: "general" },
    { en: "cold", es: "frío", de: "kalt", level: "beginner", type: "adjective", theme: "general" },
    { en: "warm", es: "cálido", de: "warm", level: "beginner", type: "adjective", theme: "general" },
    { en: "small", es: "pequeño", de: "klein", level: "beginner", type: "adjective", theme: "general" },
    { en: "large", es: "grande", de: "gross", level: "beginner", type: "adjective", theme: "general" },
    { en: "with", es: "con", de: "mit", level: "beginner", type: "other", theme: "general" },
    { en: "under", es: "bajo", de: "unter", level: "intermediate", type: "other", theme: "general" },
    { en: "over", es: "sobre", de: "über", level: "intermediate", type: "other", theme: "general" },
    { en: "easy", es: "fácil", de: "einfach", level: "intermediate", type: "adjective", theme: "general" },
    { en: "hard", es: "difícil", de: "schwer", level: "intermediate", type: "adjective", theme: "general" },
    { en: "happy", es: "feliz", de: "glücklich", level: "intermediate", type: "adjective", theme: "general" },
    { en: "sad", es: "triste", de: "traurig", level: "beginner", type: "adjective", theme: "general" }
];
